
##Block All Traffic Except for Nodes (Calico Example)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: block-api-access
  namespace: kube-system
spec:
  podSelector:
    matchLabels:
      component: apiserver
  ingress:
    - from:
        - ipBlock:
            cidr: 10.0.0.0/16  # Replace with your allowed subnet
  policyTypes:
    - Ingress

---

